language: python
dist: xenial
sudo: true
branches:
  only:
    - master
python:
  - 3.6
  - 3.7

env:
  - PYSAL_PYPI=true #testing on dependencies libpysal, esda, mapcalssify on pypi
  - PYSAL_PYPI=false

matrix:
  allow_failures:
      - python: 3.6
        env: PYSAL_PYPI=false
      - python: 3.7
        env: PYSAL_PYPI=false

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ./miniconda
  - export PATH=`pwd`/miniconda/bin:$PATH
  - conda update --yes conda
  - conda create -y -q -n test-env python=$TRAVIS_PYTHON_VERSION
  - source activate test-env

install:
  - conda install --yes pip
  - pip install -r requirements.txt
  - pip install -r requirements_tests.txt
  - if "$PYSAL_PYPI"; then
        echo 'testing pypi libpysal' && pip install libpysal;
    else
        echo 'testing git libpysal';
        pip install https://github.com/pysal/libpysal/archive/master.zip;
    fi;

script:
  - python setup.py sdist >/dev/null
  - python setup.py install
  - nosetests --verbose --with-coverage --cover-package=inequality;

notifications:
    email:
        recipients:
            - levi.john.wolf+travis@gmail.com
            - sjsrey+travis@gmail.com
            - weikang9009@gmail.com
        on_change: change
        on_failure: always

after_success:
  - coveralls
